<template>
  <v-autocomplete
    clearable
    chips
    label="Autocomplete"
    :items="[
      'California',
      'Colorado',
      'Florida',
      'Georgia',
      'Texas',
      'Wyoming',
    ]"
    multiple
    variant="outlined"
  ></v-autocomplete>
</template>
